### ISSUE TITLE
IDA Home and lumina.

### ISSUE THREAD

**Issue by Coriana** [zhangyoufu/lumina#2]
IDA Home uses the Lumina server to do decompiles, I notice you haven't got any provisions for proxying that. would you care to collaborate towards mapping out those functions and adding them in?

**Comment by zhangyoufu** [comment]
Implemented on master.

Both `PKT_DECOMPILE` & `PKT_DECOMPILE_RESULT` contains a single opaque bytevec_t. I have no idea how to interprete that data.
